### PR TITLE
ThemePicker: Actually enable color picker

### PR DESCRIPTION
**Pull request by awakened1712**
I don't see `com.android.customization.themes`, but I do see `com.google.android.apps.customization.pixel` on my phone.

I'm not sure what's the impact though. Please enlighten.

### CODE REVIEW

**Comment by ShevT** [comment]
Yes it is:
```
$ pm list packages | grep customization
package:com.crdroid.customization
package:com.google.android.apps.customization.pixel
```

**Comment by awakened1712** [comment]
> Yes it is:
> 
> ```
> $ pm list packages | grep customization
> package:com.crdroid.customization
> package:com.google.android.apps.customization.pixel
> ```

At line 19 https://github.com/crdroidandroid/android_packages_apps_ThemePicker/blob/13.0/AndroidManifest.xml#LL19-L19C68, `com.android.customization.themes` does not exist

**Comment by neobuddy89** [comment]
Below permission should check all packages on device. What is the issue here?

    <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />

https://github.com/crdroidandroid/android_packages_apps_ThemePicker/commit/2c8619c060e0515d0a2162da2d1f39d20cfeb49a

**Comment by awakened1712** [comment]
I try removing both `com.crdroid.customization` and `com.google.android.apps.customization.pixel` from the phone, and I don't see any impact. I'm not sure what's going on.

**Pull request closed without merging**
